#include "./_global.hpp"

xNetAddress ConfigTcpBindAddress;
xNetAddress ConfigServerListDownloadAddress;

xAuditAccountServerListDownloader AuditAccountServerListDownloader;
xAuthCacheServerListDownloader    AuthCacheServerListDownloader;

xPA_ClientConnectionManager ClientConnectionManager;
